import type { Deal } from '../types'

/** A fully-populated Deal with every field nulled, overridable per test. */
export function makeDeal(overrides: Partial<Deal> = {}): Deal {
  const base: Deal = {
    id: 'deal-1',
    company_name: 'Acme Holdings',
    bucket: null,
    stage: null,
    location: 'Austin, TX',
    deal_size_m: 25,
    sector_primary: 'Software',
    sector_full: null,
    subsector: null,
    security: 'First Lien',
    uop: null,
    source: null,
    timing_qtr: null,
    nda: null,
    dataroom: null,
    mgmt_meeting: null,
    ioi_offered: null,
    ioi_signed: null,
    target_close: null,
    commentary: null,
    reasons_for_passing: null,
    last_updated: null,
    updated_by: 'test',
    total_funded_m: null,
    pipeline_stage: 'screening',
    status: 'Active',
    state: null,
    next_action: null,
    sourcing_date: null,
    contact_name: null,
    contact_role: null,
    nda_date: null,
    nda_status: null,
    tenor_months: null,
    amortization: null,
    oid_pct: null,
    sofr_floor_pct: null,
    call_protection: null,
    maturity_date: null,
    total_leverage: null,
    spread_bps: null,
    base_rate: null,
    sofr_rate: null,
    all_in_rate: null,
    hold_amount_m: null,
    ltm_revenue_m: null,
    ltm_ebitda_m: null,
    ebitda_margin: null,
    revenue_growth_pct: null,
    ebitda_growth_pct: null,
    capex_m: null,
    fcf_m: null,
    dscr: null,
    fccr: null,
    interest_coverage: null,
    max_leverage_covenant: null,
    min_fccr_covenant: null,
    capex_limit_covenant_m: null,
    employees: null,
    locations_count: null,
    year_founded: null,
    risk_score: null,
    deal_team: null,
    underwriting_locked: false,
    company_id: null,
  }
  return { ...base, ...overrides }
}
